/**
 * 
 */
package ec.com.smx.sic.cliente.common.articulo;

/**
 * @author jdvasquez
 *
 */
public enum EnumRegistroEdicionMasivaDatosLogisticos {
	ARTICULO_PESO,
	ARTICULO_ALTURA,
	ARTICULO_ANCHO,
	ARTICULO_PROFUNDIDAD,
	ARTICULO_CANTIDAD_POR_PALLET,
	ARTICULO_RECIPIENTE,
	ARTICULO_UBICACION,
	ARTICULO_CANTIDAD,
	ARTICULO_RECIBE_POR_PALLET,
	ARTICULO_ES_COMPARTIDO,
	ARTICULO_AREA_ALMACENAMIENTO,
	ARTICULO_AREA_CONSERVACION,
	ARTICULO_TIENE_TARA
}
