package ec.com.smx.sic.cliente.common.articulo;

public enum EnumArticuloBusquedaSimple {
	ARTICULO_CODIGOUNICO_REPORTE,
	ARTICULO_CODIGOUNICO_FILTRO,
	ARTICULO_CODIGOBARRAS_REPORTE,
	ARTICULO_CODIGOBARRAS_FILTRO,
	ARTICULO_DESCRIPCION_REPORTE,
	ARTICULO_DESCRIPCION_FILTRO,
	ARTICULO_MARCA_REPORTE,
	ARTICULO_CODIGOPROVEEDOR_REPORTE
}
