package ec.com.smx.sic.cliente.common.articulo;

/**
 * Enumerado que representa la informacion a registrar por articulo
 * @author mgranda
 *
 */
public enum EnumSubProcesoGuardadoArticulo {
	
	ARTICULO,
	ARTICULOCLASE,
	CODIGOBARRAS,
	SEGMENTOCODIFICACION,
	ARTICULOCOMERCIAL,
	ARTICULOADICIONAL,
	ARTICULOTEMPORADA,
	ARTICULOGARANTIA,
	ARTICULOINTERNET,
	ARTICULOPROCESOLOGISTICO,
	ARTICULOMEDIDA,
	ARTICULODEFINICIONARCHIVO,
	ARTICULOETIQUETA,
	ARTICULOETIQUETAMERCANCIA,
	ARTICULODURACIONCONSERVACION,
	ARTICULOUSO,
	ARTICULOPROVEEDOR,
	ARTICULOUNIDADMANEJO,
	ARTICULOIMPUESTO,
	ARTICULOMATERIAL,
	DESCUENTOVENTAARTICULO,
	ARTICULORELACIONADO,
	ARTICULOPRECIOS,
	PRECIOSPORLOCAL,
	REGISTROSANITARIO,
	AGRUPADOR,
	ESTRUCTURACOMERCIALCLIENTE,
	LEYENDA,
	ARTICULOLOCALASIGNACION,
	ARTICULOCARACTERISTICAS,
	ARTICULOLEYMERCADO,
	ARTICULOPRECIODIFERENCIADO,
	ARTICULOALCANCE
}
