package ec.com.smx.sic.cliente.common.factory;

public final class PedidoAsistidoFactoryConstantes {
	public final static String[] CONTEXTO = new String[]{
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_CREACION_CONTEXTPATH,
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_CONFIGURACION_CONTEXTPATH,
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_MIGRACION_CONTEXTPATH,
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_SERVICIO_CONTEXTPATH,
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_MONITOREO_CONTEXTPATH,
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_FIJO_CONTEXTPATH,
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_AUDITORIAS_CONTEXTPATH,
		SICFactoryConstantes.PEDIDO_ASISTIDO_BEAN_ORDENPORPEDIDO_CONTEXTPATH
	};
}
