/**
 * 
 */
package ec.com.smx.sic.cliente.common.factory;


/**
 * 
 * @author Luis Yacchirema
 * 
 * @author vjaramillo
 *
 */
public final class ProcesamientoVentasFactoryConstantes {

	public final static String[] CONTEXTO = new String[] {
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_SERVICIO_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_ADMINISTRACION_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_ADMINISTRACION_BATCH_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_DESCUENTOS_BATCH_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_DESCUENTOS_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_RECUPERACIONES_BATCH_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_RECUPERACIONES_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_DAOS_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_VENTAS_BATCH_CONTEXPATH,
		SICFactoryConstantes.PROCESAMIENTOVENTAS_BEAN_VENTAS_CONTEXPATH
	};

}
