package ec.com.smx.sic.cliente.common.factory;


public final class RecibidoNoContabilizadoFactoryConstantes {

	/**
	 * Rutas de las configuraciones de Spring para el motor de inventarios
	 */
	public final static String[] CONTEXTO = new String[]{
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_DAO_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_CALCULO_GESTOR_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_ALMACENAMIENTO_GESTOR_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_SERVICE_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_INTEGRACION_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_TAREASPROGRAMADAS_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_TAREASPROGRAMADAS_SERVICIO_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_CONTABILIZADO_VALIDACION_GESTOR_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_COTEJADO_REPORTE_SERVICIO_BEANS,
			SICFactoryConstantes.CONTEXT_RECIBIDO_NO_COOTEJADO_REPORTE_GESTOR_BEANS,
			SICFactoryConstantes.CONTEXT_FACTURACION_AUDITORIA_PRING_BEANS,
			SICFactoryConstantes.CONTEXT_FACTURACION_CORPORATIVO_BEANS
	};
	
}
